services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: "${CERTBOT_EMAIL}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./nginx:/etc/nginx/user_conf.d
    depends_on:
      flask:
        condition: service_started
    links:
      - flask

  flask:
    build: .
    container_name: flask
    restart: unless-stopped
    environment:
      FLASK_ENV: "production"
      FLASK_DEBUG: "False"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    expose:
      - 3000
    volumes:
      - ./flask:/app

volumes:
  nginx_secrets:
