services:
  flask:
    build: .
    container_name: flask
    restart: unless-stopped
    environment:
      FLASK_ENV: "production"
      FLASK_DEBUG: "False"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    expose:
      - 3000
    volumes:
      - ./flask:/app
