services:
  flask:
    build: .
    container_name: flask
    restart: unless-stopped
    environment:
      FLASK_ENV: "production"
      FLASK_HOST: "0.0.0.0"
      FLASK_PORT: "3000"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      API_KEY: "test"
    expose:
      - 3000
    volumes:
      - ./flask:/app
